spring:
  web:
    resources:
      add-mappings: true
      cache:
        period: 11000
    #mvc:
    #static-path-pattern: "/resource/**"
  #web:
  mvc:
    hiddenmethod:
      filter:
        enabled: true